TestSeries/Models/Subject.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestSeries.Models
{
    public class Subject
    {
        public int Id { get; set; }
        public string Name { get; set; }
        [AllowHtml]
        public string Description { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<ExamSubjects> Exams { get; set; }

    }
}

TestSeries/Areas/QuestionBank/Controllers/SubjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TestSeries.Models;
using TestSeries.Infra;

namespace TestSeries.Areas.QuestionBank.Controllers
{
    public class SubjectController : App
    {
        private TestSeriesContext db = new TestSeriesContext();

        // GET: /QuestionBank/Subject/
        public async Task<ActionResult> Index()
        {
            return View(await db.Subjects.ToListAsync());
        }

        // GET: /QuestionBank/Subject/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject subject = await db.Subjects.FindAsync(id);
            if (subject == null)
            {
                return HttpNotFound();
            }
            return View(subject);
        }

        // GET: /QuestionBank/Subject/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /QuestionBank/Subject/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include="Id,Name,Description")] Subject subject)
        {
            if (ModelState.IsValid)
            {
                db.Subjects.Add(subject);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(subject);
        }

        // GET: /QuestionBank/Subject/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject subject = await db.Subjects.FindAsync(id);
            if (subject == null)
            {
                return HttpNotFound();
            }
            return View(subject);
        }

        // POST: /QuestionBank/Subject/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include="Id,Name,Description")] Subject subject)
        {
            if (ModelState.IsValid)
            {
                db.Entry(subject).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(subject);
        }

        // GET: /QuestionBank/Subject/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject subject = await db.Subjects.FindAsync(id);
            if (subject == null)
            {
                return HttpNotFound();
            }
            return View(subject);
        }

        // POST: /QuestionBank/Subject/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Subject subject = await db.Subjects.FindAsync(id);
            db.Subjects.Remove(subject);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TestSeries/Areas/QuestionBank/Views/Subject/Create.cshtml
@model TestSeries.Models.Subject

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminLayout/_LayoutAdmin.cshtml";
}

<div class="row">
    <div class="content-panel form-panel">
        <h4>Subject  <i class="fa fa-angle-right"></i>Create @Html.ActionLink("List Subject", "Index", null, new { @class = "btn btn-primary pull-right" })</h4>


        <div class="clearboth"></div>
        <hr />



        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
              
                @Html.ValidationSummary(true)

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name)
                        @Html.ValidationMessageFor(model => model.Name)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Description, new { @class = "textarea  ckeditor", row = "5", col = "6" })
                        @Html.ValidationMessageFor(model => model.Description)
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        

       
        </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script src="~/Assets/ckeditorBasic/ckeditor.js"></script>
}

TestSeries/Areas/QuestionBank/Views/Subject/Delete.cshtml
@model TestSeries.Models.Subject

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/AdminLayout/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Subject</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TestSeries/Areas/QuestionBank/Views/Subject/Details.cshtml
@model TestSeries.Models.Subject

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/AdminLayout/_LayoutAdmin.cshtml";
}

<div class="row">
    <div class="content-panel form-panel">
        <h4>Subject  <i class="fa fa-angle-right"></i>Details  <i class="fa fa-angle-right"></i>@Model.Name @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary pull-right" })</h4>


        <div class="clearboth"></div>
        <hr />
       

        <div>

            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>

                <dd>
                    @Html.Raw(Model.Description)
                </dd>

            </dl>
        </div>
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary " }) |
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
        </p>

</div>

TestSeries/Areas/QuestionBank/Views/Subject/Edit.cshtml
@model TestSeries.Models.Subject

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLayout/_LayoutAdmin.cshtml";
}

<div class="row">
    <div class="content-panel form-panel">
        <h4>Subject  <i class="fa fa-angle-right"></i>Edit  <i class="fa fa-angle-right"></i>@Model.Name @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary pull-right" })</h4>


        <div class="clearboth"></div>
        <hr />



        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
             
                
                @Html.ValidationSummary(true)
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name)
                        @Html.ValidationMessageFor(model => model.Name)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Description, new { @class = "textarea  ckeditor", row = "5", col = "6" })
                        @Html.ValidationMessageFor(model => model.Description)
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

    </div>

TestSeries/Areas/QuestionBank/Views/Subject/Index.cshtml
@model IEnumerable<TestSeries.Models.Subject>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout/_LayoutAdmin.cshtml";
}

<div class="row">
    <div class="content-panel form-panel">
        <h4><i class="fa fa-angle-right"></i>Subjects @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary pull-right" })</h4>


        <div class="clearboth"></div>
        <hr>


        <table class="table table-striped table-advance table-hover">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.Raw(item.Description)
                    </td>

                    <td>
                        <a href="@Url.Action("Details","Subject",new{id=item.Id})" class="btn btn-success btn-xs"><i class="fa fa-check"></i></a>
                        <a href="@Url.Action("Edit","Subject",new{id=item.Id})" class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></a>
                        <a href="@Url.Action("Delete","Subject",new{id=item.Id})" class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></a>
                    </td>
                    @*<td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                        </td>*@
                </tr>
            }

        </table>

    </div>
</div>